name: default
config:
  features.images: 'true'
  features.networks: 'true'
  features.networks.zones: 'true'
  features.profiles: 'true'
  features.storage.buckets: 'true'
  features.storage.volumes: 'true'
